### ISSUE TITLE
5 sugestões do que acredito que sejam melhorias

### ISSUE THREAD

**Issue by ofernandofilo** [FalGamerr/Menu-Scripts#1]
(0) add "chcp 65001" antes de :inicio para permitir o uso de acentos

talvez seja necessário mudar a fonte do cmd em sistemas mais antigos ('lucinda' ou outros)

(1) add acentos

após ativa página UTF-8 com o comando anterior, acentos devem ser exibidos sem prejuízo

(2) evitar repetição de código com uso de função

2.a chame uma função com a passagem de parâmetro, sugestão: "call :func FAL"

    call :funcaolimpar FAL

2.b add um novo label após o cls do label anterior, como:

    :limpar
    cls
    REM ...

para 

    :limpar
    cls
    :funcaolimpar
    REM ...

2.3 add um retorno de função condicionado à presença do parâmetro "FAL" antes do primeiro combo "pause + goto" na função

    if "%1"=="FAL" exit /B

(3) mudar ordem de comandos em :otimizar, sfc pós dism

use "sfc /scannow" após "DISM.exe /Online /Cleanup-image /Restorehealth"

source: https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca

(4) evitar o travamento do script ao ser executado em drives externos

assim, ao invés de deixar o código dinâmico em relação ao drive, força-lo para ser executado sempre de %temp%.

como o script não precisa de fato usar a sua pasta raiz, ele pode ser executado sem prejuízo inicial em %temp%.

mudar :UACprompt de

    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"="
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

para

    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    REM set params = %*:"="
    REM echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"
    copy %0 "%temp%\fgms.cmd" /y
    echo UAC.ShellExecute "cmd.exe", "/K %temp%\fgms.cmd", "", "runas", 1 >> "%temp%\getadmin.vbs"

e também, mudar o comando de saída de:

    if "%opcao%"=="0" exit

para:

    if "%opcao%"=="0" call del "%temp%\fgms.cmd" && exit

o uso de call aparentemente deixa mais confiável o apagar do arquivo.

por fim, o problema parece estar relacionado ao uso de UAC. ao usar UAC a conta administrativa perde controle das unidades de externas adicionadas pelo usuário. tendo que realizar alterações de registro e re-inicialização ou, como proposto, forçar o script a executar sempre de %temp%.

source: https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/how-it-works
source: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee844140(v=ws.10)?redirectedfrom=MSDN
source: https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/user-account-control-and-remote-restriction

_o/

**Comment by FalGamerr** [comment]
Muito obrigado, irei implementar aos poucos nas próximas versões pois preciso estudar um pouco sobre como implementar isso e que mudança isso fará, algumas mais rápidas e outras mais lentamente, agradeço grandemente e na próxima versão teremos crédito seu

**Comment by FalGamerr** [comment]
fiz quase todas as requests, upei a versão 1.2 publicamente, a solução do problema do UAC será estudada para implementar na versão 1.3, voi fechar o request por aqui mas ainda implementarei
