### ISSUE TITLE
2 novas sugestões de alterações

### ISSUE THREAD

**Issue by ofernandofilo** [FalGamerr/Menu-Scripts#2]
[1] - permitir iniciar o script de unidade externa

mudar este trecho:

    :UACPrompt
        echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
        set params = %*:"="
        echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"
        "%temp%\getadmin.vbs"
        del "%temp%\getadmin.vbs"
        exit /B
    :gotAdmin

para:

    :UACPrompt
        echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
         
        REM set params = %*:"="
        REM echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"
        copy %0 "%temp%\fgms.cmd" /y
        echo UAC.ShellExecute "cmd.exe", "/K %temp%\fgms.cmd", "", "runas", 1 >> "%temp%\getadmin.vbs"
        
        "%temp%\getadmin.vbs"
        del "%temp%\getadmin.vbs"
        exit /B

    :gotAdmin

apenas duas linhas foram comentadas, preservando o código original, e duas linhas foram adicionadas, alterando o comportamento.

a alteração força a criação de uma cópia do script na pasta temporária do sistema em C: e assim funciona mesmo quando o script é iniciado de outras unidades.

[2] - corrigir acentuação do defrag

mudar o trecho:

    sfc /scannow
    for /f "skip=1" %%d in ('wmic logicaldisk get caption') do (
        defrag %%d /h /u /v
    )
    chkdsk /F /R

para:

    sfc /scannow
    chcp 1252 > nul
    for /f "skip=1" %%d in ('wmic logicaldisk get caption') do (
        defrag %%d /h /u /v
    )
    chcp 65001 > nul
    chkdsk /F /R

foram adicionadas duas linhas... uma logo antes e uma logo após ao laço FOR.

a saída está direcionada para '> nul' o que faz o programa não emitir aviso durante execução, sendo portanto transparente ao usuário.

a solução não me parece elegante, mas foi a única que encontrei... e o problema só ocorreu na versão portuguesa do Windows.

[3] - **bônus**: lembrar de alterar a versão para 1.3

_o/

**Comment by FalGamerr** [comment]
corrigido
